products = [
  {
    '_id': '1',
    'name': 'Apple iPhone 12 128GB Purple Akıllı Telefon',
    'image': '/images/1.jpg',
    'description':
      'https://www.teknosa.com/apple-iphone-12-128gb-purple-akilli-telefon-p-125078063',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 11.199,
    'countInStock': 10,
    'rating': 5,
    'numReviews': 1,
  },
  {
    '_id': '2',
    'name': 'Apple MacBook Pro 16" Intel Core i9 2.3GHz 1TB Space Grey Notebook MVVK2TU/A',
    'image': '/images/2.jpg',
    'description':
      'https://www.teknosa.com/apple-macbook-pro-16-intel-core-i9-23ghz-1tb-space-grey-notebook-mvvk2tua-p-125034027',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 29.399,
    'countInStock': 10,
    'rating': 5,
    'numReviews': 35,
  },
  {
    '_id': '3',
    'name': 'AppIe İPad Pro MXAY2TU/A Wifi 1TB 12.9 inç Silver Tablet',
    'image': '/images/3.jpg',
    'description':
      'https://www.teknosa.com/appie-ipad-pro-mxay2tua-wifi-1tb-129-inc-silver-tablet-p-125047149',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 14.249,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 1,
  },
  {
    '_id': '4',
    'name': 'Apple MHK03TU/A iMac Intel Core i3 8GB 256GB SSD MacOS 21.5" FHD All In One Bilgisayar',
    'image': '/images/4.jpg',
    'description':
      'https://www.teknosa.com/apple-mhk03tua-imac-intel-core-i3-8gb-256gb-ssd-macos-215-fhd-all-in-one-bilgisayar-p-125011903',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 14.019,
    'countInStock': 0,
    'rating': 0,
    'numReviews': 0,
  },
  {
    '_id': '5',
    'name': 'Apple Watch Nike Seri 6 40mm Space Gray Alüminyum Kasa ve Antrasit Spor Kordon M00X3TU/A',
    'image': '/images/5.jpg',
    'description':
      'https://www.teknosa.com/apple-watch-nike-seri-6-40mm-space-gray-aluminyum-kasa-antrasit-spor-kordon-m00x3tua-p-145061234',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 3.799,
    'countInStock': 10,
    'rating': 5,
    'numReviews': 1,
  },
  {
    '_id': '6',
    'name': 'Apple AirPods 2.Nesil ve Şarj Kutusu (MV7N2TU/A)',
    'image': '/images/6.jpg',
    'description':
      'https://www.teknosa.com/apple-airpods-2nesil-sarj-kutusu-mv7n2tua-p-145058647',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 1.599,
    'countInStock': 10,
    'rating': 5,
    'numReviews': 150,
  },
]
